// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySqlContext))]
    partial class MySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "Camiseta",
                            Description = "is simply dummy text of the printing and typesetting industry. n printer",
                            ImageUrl = "https://m.media-amazon.com/images/I/51yoMkiWWHL._AC_SX522_.jpg",
                            Name = "Name",
                            Price = 69m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Camiseta",
                            Description = "is simply dummy text of the printing and typesetting industry. n printer",
                            ImageUrl = "https://m.media-amazon.com/images/I/51yoMkiWWHL._AC_SX522_.jpg",
                            Name = "Name",
                            Price = 69m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Camiseta",
                            Description = "is simply dummy text of the printing and typesetting industry. n printer",
                            ImageUrl = "https://m.media-amazon.com/images/I/51yoMkiWWHL._AC_SX522_.jpg",
                            Name = "Name",
                            Price = 69m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Camiseta",
                            Description = "is simply dummy text of the printing and typesetting industry. n printer",
                            ImageUrl = "https://m.media-amazon.com/images/I/51yoMkiWWHL._AC_SX522_.jpg",
                            Name = "Name",
                            Price = 69m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Camiseta",
                            Description = "is simply dummy text of the printing and typesetting industry. n printer",
                            ImageUrl = "https://m.media-amazon.com/images/I/51yoMkiWWHL._AC_SX522_.jpg",
                            Name = "Name",
                            Price = 69m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Camiseta",
                            Description = "is simply dummy text of the printing and typesetting industry. n printer",
                            ImageUrl = "https://m.media-amazon.com/images/I/51yoMkiWWHL._AC_SX522_.jpg",
                            Name = "Name",
                            Price = 69m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Camiseta",
                            Description = "is simply dummy text of the printing and typesetting industry. n printer",
                            ImageUrl = "https://m.media-amazon.com/images/I/51yoMkiWWHL._AC_SX522_.jpg",
                            Name = "Name",
                            Price = 69m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
